<a href="https://colab.research.google.com/github/nuraynazarli/NumPy/blob/main/numpy2_alistirma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr=arr.reshape(15,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
# 2
arr=np.random.randint(0,200,60)
arr

array([ 43,  76, 110, 180,   2,  41, 140, 192,  62, 162,  76, 172,  22,
       158, 118,  15, 155, 199, 184, 169, 110,  57,   7,  51,  16,  64,
       173,   9, 188, 104, 105, 174, 191,  40,  39, 174,  91, 182, 144,
        23,  14,  42,  26, 133,  11, 186, 173, 134,  20, 127, 158, 191,
       181, 198, 175, 197, 185, 108, 196, 190])

In [ ]:
arr=arr.reshape(2,3,-1)
arr

array([[[ 43,  76, 110, 180,   2,  41, 140, 192,  62, 162],
        [ 76, 172,  22, 158, 118,  15, 155, 199, 184, 169],
        [110,  57,   7,  51,  16,  64, 173,   9, 188, 104]],

       [[105, 174, 191,  40,  39, 174,  91, 182, 144,  23],
        [ 14,  42,  26, 133,  11, 186, 173, 134,  20, 127],
        [158, 191, 181, 198, 175, 197, 185, 108, 196, 190]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 3, 10)

In [ ]:
# 3
arr=np.random.randint(0,100,(2,10))
arr

array([[86, 29, 61, 54, 26, 55, 85, 26, 76, 67],
       [ 3, 68, 12, 66, 41, 30, 16, 65, 95, 58]])

In [ ]:
arr1=arr.reshape(-1)
arr1

array([86, 29, 61, 54, 26, 55, 85, 26, 76, 67,  3, 68, 12, 66, 41, 30, 16,
       65, 95, 58])

In [ ]:
arr1.ndim


1

In [ ]:
arr1.shape

(20,)

In [ ]:
# 4
arr2d=np.random.randint(0,10,(2,6))
arr2d

array([[4, 0, 0, 9, 6, 3],
       [7, 5, 9, 3, 8, 5]])

In [ ]:
for x in arr2d:
  for y in x:
    print(y)

4
0
0
9
6
3
7
5
9
3
8
5


In [ ]:
for x in np.nditer(arr2d):
  print(x)

4
0
0
9
6
3
7
5
9
3
8
5


In [ ]:
# 5
arr1=np.arange(5,31,5)
arr2=np.arange(1,7)

In [ ]:
arr1

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1[0]+arr2[0]

6

In [ ]:
arr1[0]-arr2[0]

4

In [ ]:
arr1[0]*arr2[0]

5

In [ ]:
arr1[0]/arr2[0]

5.0

In [ ]:
# 6
arr=np.random.randint(0,100,10)
arr

array([92, 89, 12, 42, 55, 24, 71, 10,  0, 35])

In [ ]:
arr.sum()

430

In [ ]:
arr.mean()

43.0

In [ ]:
arr.max()

92

In [ ]:
arr.var()

977.0

In [ ]:
arr.std()

31.25699921617557

In [ ]:
# 7
arr1=np.arange(0,20)
arr2=np.arange(500,531)

In [ ]:
arr1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [ ]:
# 8
arr1=np.arange(15,51)
arr2=np.arange(10,101)

In [ ]:
arr3=np.concatenate([arr1,arr2],axis=0)
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr3[25:51]=888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# 9
arr1=np.arange(0,40).reshape(8,5)
arr2=np.arange(320,360).reshape(8,5)

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [ ]:
np.concatenate([arr1,arr2],axis=1)

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [ ]:
# 10
arr1=np.arange(0,40).reshape(2,-1,5)
arr2=np.arange(320,360).reshape(2,-1,5)

In [ ]:
arr1.ndim

3

In [ ]:
np.concatenate([arr1,arr2],axis=2)

array([[[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
        [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
        [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
        [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339]],

       [[ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
        [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
        [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
        [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]]])

In [ ]:
np.stack([arr1,arr2],axis=2)

array([[[[  0,   1,   2,   3,   4],
         [320, 321, 322, 323, 324]],

        [[  5,   6,   7,   8,   9],
         [325, 326, 327, 328, 329]],

        [[ 10,  11,  12,  13,  14],
         [330, 331, 332, 333, 334]],

        [[ 15,  16,  17,  18,  19],
         [335, 336, 337, 338, 339]]],


       [[[ 20,  21,  22,  23,  24],
         [340, 341, 342, 343, 344]],

        [[ 25,  26,  27,  28,  29],
         [345, 346, 347, 348, 349]],

        [[ 30,  31,  32,  33,  34],
         [350, 351, 352, 353, 354]],

        [[ 35,  36,  37,  38,  39],
         [355, 356, 357, 358, 359]]]])

In [ ]:
# 11
arr=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [ ]:
np.where(arr==5)

(array([ 5, 13]),)

In [ ]:
# 12
np.where(arr%2 !=1)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [ ]:
# 13
np.where(arr>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [ ]:
# 14
np.where(arr%5 !=1)

(array([ 1,  2,  3,  4,  5,  6,  7, 10, 11, 13]),)

In [ ]:
# 15
np.random.randint(85,100,1)

array([87])

In [ ]:
# 16
np.random.randint(10,100,(3,3))

array([[83, 71, 43],
       [58, 28, 29],
       [29, 65, 86]])

In [ ]:
# 17
arr=np.arange(35,61)
arr

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [ ]:
np.random.choice(arr)

57

In [ ]:
# 18
arr=np.array([3, 8, 10, 53,3, 3, 8, 10, 53,3]).reshape(2,5)
arr

array([[ 3,  8, 10, 53,  3],
       [ 3,  8, 10, 53,  3]])