<a href="https://colab.research.google.com/github/nuraynazarli/NumPy/blob/main/numpy1_alistirma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1
arr3d=np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
arr3d

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [ ]:
arr3d.ndim

3

In [ ]:
# 2
np.arange(34,113,6)


array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [ ]:
# 3
np.linspace(50,500,91,dtype=int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [ ]:
# 4
np.logspace(2,5,8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [ ]:
# 5
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 6
np.zeros((6,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# 7
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# 8
df=np.zeros((8,8),dtype=int)
df[0,0]=1
df

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 9
df=np.zeros((5,5),dtype=int)
np.fill_diagonal(df,3)
df

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [ ]:
# 10
np.random.rand(6)

array([0.56086418, 0.80884029, 0.47954366, 0.97702831, 0.30186051,
       0.89294297])

In [ ]:
# 11
arr=np.random.randint(50,101,(5,2))
arr

array([[97, 80],
       [53, 86],
       [90, 97],
       [71, 91],
       [89, 57]])

In [ ]:
arr.shape

(5, 2)

In [ ]:
# 12
arr=np.random.randint(100,1001,(2,5,5))
arr

array([[[515, 875, 124, 161, 936],
        [133, 441, 939, 718, 873],
        [418, 870, 535, 942, 638],
        [686, 815, 637, 539, 352],
        [894, 165, 746, 828, 682]],

       [[554, 470, 428, 191, 635],
        [745, 312, 180, 572, 695],
        [649, 408, 339, 484, 233],
        [244, 442, 768, 396, 510],
        [204, 130, 857, 710, 600]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 5, 5)

In [ ]:
# 13
arr=np.random.randint(0,101,10)
arr

array([ 9, 96, 78, 16,  1, 58, 34, 57, 40, 76])

In [ ]:
arr.max()

96

In [ ]:
arr.argmax()

1

In [ ]:
arr.min()

1

In [ ]:
arr.argmin()

4

In [ ]:
# 14
arr=np.random.randint(300,501,(2,2,5))
arr

array([[[405, 440, 380, 320, 342],
        [301, 397, 314, 328, 442]],

       [[493, 449, 367, 453, 457],
        [310, 466, 455, 488, 391]]])

In [ ]:
arr[0,1,0]  #min

301

In [ ]:
arr[1,0,0]  #max

493

In [ ]:
# 15
arr=np.arange(0,51)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
arr[20:35]=500

In [ ]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])