<a href="https://colab.research.google.com/github/nuraynazarli/NumPy/blob/main/numpy2_alistirma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# 1. 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
arr=arr.reshape(15,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [5]:
# 2. 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr=np.random.randint(0,200,60)
arr

array([ 30, 120, 128,  32, 178,  47, 188,  14,  32,  74, 162,  74,  34,
        76, 136,   5, 175, 149,  96, 125, 124, 122,  74, 167, 164, 114,
       180, 161, 192, 187,  93, 170,  37, 117, 178, 191, 102, 172,   3,
       197,  41, 101, 138,  60,  56, 113,  30, 177,  50, 176,  57, 100,
       127, 121,  29, 186, 187,  54,  55, 199])

In [6]:
arr=arr.reshape(2,3,-1)
arr

array([[[ 30, 120, 128,  32, 178,  47, 188,  14,  32,  74],
        [162,  74,  34,  76, 136,   5, 175, 149,  96, 125],
        [124, 122,  74, 167, 164, 114, 180, 161, 192, 187]],

       [[ 93, 170,  37, 117, 178, 191, 102, 172,   3, 197],
        [ 41, 101, 138,  60,  56, 113,  30, 177,  50, 176],
        [ 57, 100, 127, 121,  29, 186, 187,  54,  55, 199]]])

In [7]:
arr.ndim

3

In [8]:
arr.shape

(2, 3, 10)

In [9]:
# 3. 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr=np.random.randint(0,100,(2,10))
arr

array([[71, 99, 94, 60, 14, 12, 56, 63,  1,  7],
       [76, 93, 18, 26, 63, 10, 59, 75, 58, 17]])

In [10]:
arr1=arr.reshape(-1)
arr1

array([71, 99, 94, 60, 14, 12, 56, 63,  1,  7, 76, 93, 18, 26, 63, 10, 59,
       75, 58, 17])

In [11]:
arr1.ndim


1

In [12]:
arr1.shape

(20,)

In [14]:
# 4. İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
arr2d=np.random.randint(0,10,(2,6))
arr2d

array([[2, 3, 8, 1, 3, 0],
       [3, 8, 3, 5, 8, 2]])

In [15]:
for x in arr2d:
  for y in x:
    print(y)

2
3
8
1
3
0
3
8
3
5
8
2


In [16]:
for x in np.nditer(arr2d):
  print(x)

2
3
8
1
3
0
3
8
3
5
8
2


In [17]:
# 5. 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun. Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
arr1=np.arange(5,31,5)
arr2=np.arange(1,7)

In [18]:
arr1

array([ 5, 10, 15, 20, 25, 30])

In [19]:
arr2

array([1, 2, 3, 4, 5, 6])

In [20]:
arr1[0]+arr2[0]

6

In [21]:
arr1[0]-arr2[0]

4

In [22]:
arr1[0]*arr2[0]

5

In [23]:
arr1[0]/arr2[0]

5.0

In [24]:
# 6. 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
arr=np.random.randint(0,100,10)
arr

array([10, 99, 19, 91, 94, 55, 21, 74, 78, 37])

In [25]:
arr.sum()

578

In [26]:
arr.mean()

57.8

In [27]:
arr.max()

99

In [28]:
arr.var()

1036.56

In [29]:
arr.std()

32.19565188033937

In [30]:
# 7. 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
arr1=np.arange(0,20)
arr2=np.arange(500,531)

In [31]:
arr1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
arr2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [33]:
np.concatenate([arr1,arr2],axis=0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [34]:
# 8. 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
arr1=np.arange(15,51)
arr2=np.arange(10,101)

In [35]:
arr3=np.concatenate([arr1,arr2],axis=0)
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [36]:
arr3[25:51]=888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
# 9. 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
arr1=np.arange(0,40).reshape(8,5)
arr2=np.arange(320,360).reshape(8,5)

In [38]:
np.concatenate([arr1,arr2],axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [39]:
np.concatenate([arr1,arr2],axis=1)

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [40]:
# 10. 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
arr1=np.arange(0,40).reshape(2,-1,5)
arr2=np.arange(320,360).reshape(2,-1,5)

In [41]:
arr1.ndim

3

In [42]:
np.concatenate([arr1,arr2],axis=2)

array([[[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
        [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
        [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
        [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339]],

       [[ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
        [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
        [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
        [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]]])

In [43]:
np.stack([arr1,arr2],axis=2)

array([[[[  0,   1,   2,   3,   4],
         [320, 321, 322, 323, 324]],

        [[  5,   6,   7,   8,   9],
         [325, 326, 327, 328, 329]],

        [[ 10,  11,  12,  13,  14],
         [330, 331, 332, 333, 334]],

        [[ 15,  16,  17,  18,  19],
         [335, 336, 337, 338, 339]]],


       [[[ 20,  21,  22,  23,  24],
         [340, 341, 342, 343, 344]],

        [[ 25,  26,  27,  28,  29],
         [345, 346, 347, 348, 349]],

        [[ 30,  31,  32,  33,  34],
         [350, 351, 352, 353, 354]],

        [[ 35,  36,  37,  38,  39],
         [355, 356, 357, 358, 359]]]])

In [44]:
# 11. [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
arr=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [45]:
np.where(arr==5)

(array([ 5, 13]),)

In [46]:
# 12. Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
np.where(arr%2 !=1)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [47]:
# 13. Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun. 
np.where(arr>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [48]:
# 14. Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
np.where(arr%5 !=1)

(array([ 1,  2,  3,  4,  5,  6,  7, 10, 11, 13]),)

In [49]:
# 15. 85-100(100 dahil) arasından rastgele 1 tam sayı seçin.
np.random.randint(85,100,1)

array([95])

In [50]:
# 16. İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
np.random.randint(10,100,(3,3))

array([[27, 25, 43],
       [82, 63, 52],
       [57, 60, 22]])

In [51]:
# 17. 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
arr=np.arange(35,61)
arr

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [52]:
np.random.choice(arr)

42

In [53]:
# 18. Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
arr=np.array([3, 8, 10, 53,3, 3, 8, 10, 53,3]).reshape(2,5)
arr

array([[ 3,  8, 10, 53,  3],
       [ 3,  8, 10, 53,  3]])