<a href="https://colab.research.google.com/github/nuraynazarli/NumPy/blob/main/numpy_bitirme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. NumPy kütüphanesi np kısaltması ile import edin.
import numpy as np

In [3]:
# 2. 10 tane 0 değerinden oluşan bir array oluşturun.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 3. 10 tane 1 değerinden oluşan bir array oluşturun.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 4. 10 tane 5 değerinden oluşan bir array oluşturun.
arr=np.zeros(10)
arr[0:10]=5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
# 5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım.
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
# 6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil).
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
# 7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım.
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# 8. 3x3 boyutlarında birim matris oluşturun.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# 9. NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun.
np.random.rand()

0.4130513838769331

In [11]:
# 10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım.
np.random.randn(25)

array([-0.92126184, -1.27399879,  3.36788756,  2.67989527,  1.47889434,
        0.4637196 , -0.83926519,  1.09768383,  0.29977042, -0.45620083,
       -0.67815798,  1.56427202, -1.00037638, -0.27867669,  0.73425119,
       -0.27397041, -0.13519893,  0.4230967 ,  0.93970683, -0.28111149,
        0.31307953,  0.89860577,  0.83225488,  1.93410421, -0.59471643])

In [12]:
# 11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın.
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [13]:
# 12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun.
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
# 13. Aşağıda verilen matrisleri oluşturmaya çalışın.
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
# 14. Aşağıda verilen degeri çıkarmaya çalışın.
mat[3,4]

20

In [17]:
# 15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun.
mat[:3,1]

array([ 2,  7, 12])

In [18]:
# 16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun.
mat[4,:]

array([21, 22, 23, 24, 25])

In [19]:
# 17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun.
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
# 18. Mat arrayindeki bütün değerlerin toplamını bulun.
mat.sum()

325

In [21]:
# 19. Mat arrayindeki değerlerin standart sapmasını bulun.
mat.std()

7.211102550927978

In [22]:
# 20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun.
mat.sum(axis=0)

array([55, 60, 65, 70, 75])